[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
co2e_escrow = "FsqvhRRiENRHLncK3GKMitZT1V126pXGpT2dtVEHhMkf"

[programs.devnet]
co2e_escrow = "FsqvhRRiENRHLncK3GKMitZT1V126pXGpT2dtVEHhMkf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nokitha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
